# An action for filtering pull requests and issues from first-time contributors.
# https://github.com/marketplace/actions/first-interaction

name: Greetings

on: [pull_request, issues, discussions]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you. Kindly read contributiing.md, code_of_conduct.md and styleguide.md'
        pr-message: 'Thank you. Kindly read contributiing.md, code_of_conduct.md and styleguide.md'
